all: matlab

base="/home/guivarch/Documents/Enseignements/18-19/Calcul Scientifique/Projet/Séance 2/Projet_TP2_Fournitures/code_fourni"

matlab:
	rm  -f ${base}/Matlab/*
	cp `cat ./liste_matlab.txt` ${base}/Matlab

